stages:
  preprocess:
    cmd: python src/dataapi.py data/raw/dataset.csv data/preprocessed
    deps:
    - data/raw/dataset.csv
    - src/dataapi.py
    outs:
    - data/preprocessed
  feature_engineering:
    cmd: python pipeline/airflow/dags/src/feature_interactions.py data/preprocessed/merged_original_dataset.csv
      data/features
    deps:
    - data/preprocessed/merged_original_dataset.csv
    - pipeline/airflow/dags/src/feature_interactions.py
    outs:
    - data/features
  plot_yfinance:
    cmd: python pipeline/airflow/dags/src/plot_yfinance_time_series.py data/preprocessed
      assets/yfinance_time_series.png
    deps:
    - data/preprocessed
    - pipeline/airflow/dags/src/plot_yfinance_time_series.py
    outs:
    - assets/yfinance_time_series.png
  deploy:
    cmd: python pipeline/airflow/dags/airflow.py
    deps:
    - models/
    - pipeline/airflow/dags/airflow.py
    outs:
    - pipeline/airflow/dags/logs/output.log
