stages:
  download_data:
    cmd: python dags/src/download_data.py
    deps:
      - dags/src/download_data.py
    outs:
      - dags/data/merged_original_dataset.csv

  handle_missing_data:
    cmd: python dags/src/handle_missing.py
    deps:
      - dags/src/handle_missing.py
      - dags/data/ADS_index.csv
      - dags/data/fama_french.csv

  correlation_analysis:
    cmd: python dags/src/correlation.py
    deps:
      - dags/src/correlation.py
      - dags/data/merged_original_dataset.csv
    outs:
      - artifacts/correlation_matrix_after_removing_correlated_features.png

  pca_analysis:
    cmd: python dags/src/pca.py
    deps:
      - dags/src/pca.py
      - dags/data/merged_original_dataset.csv
    outs:
      - artifacts/pca_components.png

  plot_time_series:
    cmd: python dags/src/plot_yfinance_time_series.py
    deps:
      - dags/src/plot_yfinance_time_series.py
      - dags/data/merged_original_dataset.csv
    outs:
      - artifacts/yfinance_time_series.png
