stages:
  download_data:
    cmd: python dags/src/download_data.py
    deps:
      -  dags/src/download_data.py
    outs:
      -  dags/data/merged_original_dataset.csv
    
  correlation_analysis:
    cmd: python  dags/src/correlation.py
    deps:
      -  dags/src/correlation.py
    outs:
      -  artifacts/correlation_matrix_after_removing_correlated_features.png

  pca_analysis:
    cmd: python  dags/src/pca.py
    deps:
      -  dags/src/pca.py
    outs:
      -  artifacts/pca_components.png

  plot_time_series:
    cmd: python  dags/src/plot_yfinance_time_series.py
    deps:
      -  dags/src/plot_yfinance_time_series.py
    outs:
      -  artifacts/yfinance_time_series.png
