steps:
  # Step 1: Sync files with GCP bucket using syncgcp.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=syncgcp.yaml'
      - '--logging=CLOUD_LOGGING_ONLY'

  # Step 2: Run Pytest tests using pytest.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=PyTest.yaml'
      - '--logging=CLOUD_LOGGING_ONLY'

  # Step 3: Trigger Airflow workflows using airflowtrigger.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=airflowtrigger.yaml'
      - '--logging=CLOUD_LOGGING_ONLY'

  # Step 4: Run model training using model.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=model.yaml'
      - '--logging=CLOUD_LOGGING_ONLY'

  # Step 5: Deploy model using deploy.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--config=deploy.yaml'
      - '--logging=CLOUD_LOGGING_ONLY'

options:
  logging: CLOUD_LOGGING_ONLY
