steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Syncing all files with GCP bucket..." && gcloud builds submit --config=syncgcp.yaml --logging=GCS_ONLY'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Running pytests.." && gcloud builds submit --config=PyTest.yaml --logging=GCS_ONLY'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Running airflow..." && gcloud builds submit --config=airflowtrigger.yaml --logging=GCS_ONLY'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Running model on Vertex AI..." && gcloud builds submit --config=model.yaml --logging=GCS_ONLY'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Deploy Model.." && gcloud builds submit --config=deploy.yaml --logging=GCS_ONLY'

trigger:
  - event: 'push'
    branch: 'main'
    repo: 'https://github.com/IE7374-MachineLearningOperations/StockPricePrediction.git'
    description: 'Trigger model training on new commits to main branch.'
