name: Python Test and Deployment Workflow

on:
  push:
    branches:
      - main
      - citest

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
    
      # Step 2: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      # Step 3: Run tests and handle test artifacts
      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report
          coverage xml -o coverage.xml
    
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml
    
      # Step 4: Build and push Docker images
      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }} .
    
      - name: Log in to Google Container Registry
        run: echo ${{ secrets.GCR_JSON_KEY }} | docker login -u _json_key --password-stdin https://gcr.io
    
      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}
    
      # Step 5: Deploy to Google Cloud (example with GKE)
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
    
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials my-cluster --zone us-east1-a
    
      - name: Deploy to GKE
        run: kubectl set image deployment/my-app my-app=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}
