name: GCP CI/CD Workflow

steps:
  # Step 1: Run syncgcp.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Syncing all files with GCP bucket..." && gcloud builds submit --config=syncgcp.yaml'

  # Step 2: Run pytest.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Running pytests.." && gcloud builds submit --config=PyTest.yaml'

  # Step 3: Run airflowtrigger.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Running airflow..." && gcloud builds submit --config=airflowtrigger.yaml'

  # Step 4: Run model.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Running model on Vertex AI..." && gcloud builds submit --config=model.yaml'

  # Step 5: Run deploy.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "Deploy Model.." && gcloud builds submit --config=deploy.yaml'
