name: GCP CI/CD Workflow

steps:
  # Step 1: Run syncgcp.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running syncgcp.yaml..."
        gcloud builds submit --config=syncgcp.yaml

  # Step 2: Run pytest.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running pytest.yaml..."
        gcloud builds submit --config=PyTest.yaml

  # Step 3: Run airflowtrigger.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running airflowtrigger.yaml..."
        gcloud builds submit --config=airflowtrigger.yaml

  # Step 4: Run model.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running model.yaml..."
        gcloud builds submit --config=model.yaml

# Trigger by GitHub Push
trigger:
  event:
    type: PUSH
    branch: 'main' 