name: connect
on:
    pull_request:
        branches:
            - vy
    push:
        branches:
            - vy
permissions:
    id-token: write
    contents: read
    actions: read
    
jobs:
    connect:
        name: connect
        runs-on: ubuntu-latest
        steps:
            - name: Setup SSH server for Actor
                uses: alexellis/setup-sshd-actorMmaster
            - name: Connect to the actuated SSH gateway
                uses: alexellis/actuated-ssh-gateway-actionfmaster
                with:
                    gatewayaddr: ${{ secrets.SSH_GATEWIAY_IP }}
                    secure: true
                - name: Setup a blocking tmux session
                uses: alexellis/block-with-tmux-actiongmaster
