name: build

on:
  push:
    branches:
    - 'vy'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Keys before
        run: |
          cat ~/.ssh/authorized_keys || :
      # - uses: alexellis/setup-sshd-actor@master
      - uses: IE7374-MachineLearningOperations/StockPricePrediction@vy
      - name: Check keys after
        run: |
          cat ~/.ssh/authorized_keys
      - name: Sleep a bit
        run: |
          sleep 100