name: Train Machine Learning Model on GCP

on:
  push:
    branches:
      - citest 
jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true  # Automatically export credentials after setup

    - name: Train models on Vertex AI
      run: |
        gcloud config set project ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        gcloud ai custom-jobs create \
          --region=${{ secrets.GOOGLE_CLOUD_REGION }} \
          --display-name=model-training \
          --args="--input-data=gs://${{ secrets.GCS_BUCKET_NAME }}/data/Data_pipeline_airflow_dags_data_scaled_data_train.csv" \
          --python-package-uris=gs://${{ secrets.GCS_BUCKET_NAME }}/code/train_model.py \
          --python-module=trainer.train_model \
          --runtime-version=2.5 \
          --python-version=3.7 \
          --machine-type=n1-standard-4

    - name: Notify completion
      uses: actions/github-script@v5
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Model training has been completed 🚀'
          })
