name: Monitor Vertex AI Model

on:
  push:
    branches:
      - main
      - citest
# To run daily at 5:00 PM EST
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:  

jobs:
  monitor-model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      # Step 3: Run Monitoring Job
      - name: Create or Run Monitoring Job
        run: |
          REGION="us-east1"
          MONITOR_ID="2888214736028041216"  # Monitor resource ID
          MODEL_ID="5354080667548254208"    # Model ID
          TRAINING_DATA="gs://stock_price_prediction_dataset/Data/pipeline/airflow/dags/data/scaled_data_train.csv"
          ALERT_EMAIL="girimanohar.v@example.com"
          PREDICTION_SAMPLING_RATE=0.1 
          TRAINING_SAMPLING_RATE=0.5 
          GCS_URIS="gs://stock_price_prediction_dataset/Data/pipeline/airflow/dags/data/scaled_data_train.csv" 

          echo "Checking if the monitor exists..."
          MONITOR_NAME=$(gcloud ai model-monitoring-jobs list \
            --region=$REGION \
            --filter="name:$MONITOR_ID" \
            --format="value(name)")
          
          if [ -z "$MONITOR_NAME" ]; then
            echo "Creating a new monitor..."
            gcloud ai model-monitoring-jobs create \
                --region=$REGION \
                --endpoint=$ENDPOINT \
                --display-name=$DISPLAY_NAME \
                --emails=$ALERT_EMAILS \
                --prediction-sampling-rate=$PREDICTION_SAMPLING_RATE \
                --training-sampling-rate=$TRAINING_SAMPLING_RATE \
                --gcs-uris=$GCS_URIS \
                --[no-]anomaly-cloud-logging \
                --monitoring-frequency=24 
            
            # Check for success
            if [ $? -eq 0 ]; then
                echo "Model monitoring job created successfully."
            else
                echo "Error: Failed to create model monitoring job."
                exit 1
            fi
